[project]
name = "example_package"
description = "This package is only to demonstrate repo structure."
license = "MIT"
keywords = ["example_package", "NI"]
version = "0.0.1dev0"
classifiers = [
  # TODO: Update classifiers as appropriate.
]
dynamic = ["dependencies"]
readme = "README.md"
authors = [{name = "NI", email = "opensource@ni.com"}]
maintainers = [] # TODO:template
requires-python = '>=3.10,<4.0'

[project.urls]
repository = "https://github.com/ni/example_package" # TODO: validate this URL
# documentation = "https://example_package.readthedocs.io/" # TODO enable this once RTD publishing is set up
changelog = "https://github.com/ni/example_package/blob/main/CHANGELOG.md" # TODO: validate this URL

[build-system]
requires = ["poetry-core>=2.1.0,<3.0"]
build-backend = "poetry.core.masonry.api"


# region: poetry configuration
[tool.poetry]
packages = [{ include = "example_package", from = "src" }]
requires-poetry = '>=2.4.0,<3.0"

[solver]
min-release-age = 14

[tool.poetry.dependencies]
# cli
click = ">=7.1.2"

# TODO: Specify your project dependencies here.

[tool.poetry.group.dev.dependencies]
# Specify additional dev dependencies here.


[tool.poetry.group.lint.dependencies]
ni-python-styleguide = ">=0.4.1"
mypy = ">=1.18.1" 
pyright = { version = ">=1.1.400", extras = ["nodejs"] }
bandit = ">=1.9.4"

[tool.poetry.group.test.dependencies]
pytest = ">=7.2"
pytest-cov = ">=4.0"
pytest-mock = ">=3.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
# The latest Sphinx requires a recent Python version.
Sphinx = [
  { version = ">=8.1", python = ">=3.10,<3.11" },
  { version = ">=8.2", python = "^3.11" },
]
sphinx-rtd-theme = ">=1.0.0"
sphinx-autoapi = ">=1.8.4"
m2r2 = ">=0.3.2"
toml = ">=0.10.2"
tomlkit = ">=0.11.0"

[tool.poetry.scripts]
# TODO: If not using a CLI, remove this section and the __main__.py file.
example-package = "example_package.__main__:_cli"

# endregion


# region: unit test configuration
[tool.pytest.ini_options]
addopts = "--doctest-modules --strict-markers"
testpaths = ["src/example_package", "tests"]
# endregion


# region: linters and formatters
[tool.ni-python-styleguide]
application-import-names = "example_package,tests"


[tool.black]
line-length = 100


[tool.mypy]
files = "examples/,scripts/,src/,tests/"
namespace_packages = true
strict = true


[tool.pyright]
include = ["examples/", "scripts/", "src/", "tests/"]

# endregion
